import type { PlanetName } from './planets';

export interface Trivia {
  planet: PlanetName;
  facts: string[];
  atmosphere?: Record<string, number>;
  notableFeatures?: string[];
}

export const TRIVIA: Trivia[] = [
  {
    planet: 'SUN',
    facts: [
      'Contains 99.86% of the mass of the entire solar system.',
      'Light takes 8 minutes 20 seconds to reach Earth.',
      'Core temperature is ~15 million °C; surface is a comparatively cool 5,778 K.',
      'Will swell into a red giant in ~5 billion years, engulfing Mercury and Venus.',
    ],
    atmosphere: { Hydrogen: 73, Helium: 25, Other: 2 },
    notableFeatures: [
      'Sunspots',
      'Solar flares',
      'Corona',
      '11-year activity cycle',
    ],
  },
  {
    planet: 'MERCURY',
    facts: [
      'A single day (sunrise to sunrise) lasts 176 Earth days.',
      'Has ice in permanently shadowed polar craters despite its proximity to the Sun.',
      'Its iron core makes up ~60% of its mass — proportionally the largest in the solar system.',
      'Shrinks slowly as its interior cools, creating cliff-like "lobate scarps".',
    ],
    atmosphere: { Oxygen: 42, Sodium: 29, Hydrogen: 22, Other: 7 },
    notableFeatures: ['Caloris Basin', 'Lobate scarps', 'Polar ice deposits'],
  },
  {
    planet: 'VENUS',
    facts: [
      'Rotates backward relative to most planets — the Sun rises in the west.',
      'A day on Venus (243 Earth days) is longer than its year (225 days).',
      'Surface pressure is equivalent to being 900 m underwater on Earth.',
      'Hottest planet in the solar system, hotter even than Mercury.',
    ],
    atmosphere: { 'Carbon Dioxide': 96, Nitrogen: 3.5, Other: 0.5 },
    notableFeatures: [
      'Maxwell Montes',
      'Sulfuric acid clouds',
      'Volcanic plains',
    ],
  },
  {
    planet: 'EARTH',
    facts: [
      'The only known planet with plate tectonics — a system that recycles surface rock.',
      'Has a strong magnetic field generated by a liquid iron outer core.',
      "The Moon stabilizes Earth's axial tilt, keeping the climate relatively stable.",
      '70% of the surface is ocean; less than 5% of it has been explored in detail.',
    ],
    atmosphere: { Nitrogen: 78, Oxygen: 21, Argon: 0.9, 'CO₂': 0.04 },
    notableFeatures: [
      'Liquid water',
      'Plate tectonics',
      'Biosphere',
      'Single large moon',
    ],
  },
  {
    planet: 'MARS',
    facts: [
      'Olympus Mons is 22 km tall — 2.5× the height of Mount Everest.',
      'Valles Marineris is a canyon system 4,000 km long, dwarfing the Grand Canyon.',
      'Polar ice caps are made of both water ice and frozen CO₂.',
      'Dust storms can engulf the entire planet for months.',
    ],
    atmosphere: { 'Carbon Dioxide': 95, Nitrogen: 2.7, Argon: 1.6, Other: 0.7 },
    notableFeatures: [
      'Olympus Mons',
      'Valles Marineris',
      'Polar caps',
      'Phobos & Deimos',
    ],
  },
  {
    planet: 'JUPITER',
    facts: [
      'Has 95 known moons, including the four large Galilean satellites.',
      'The Great Red Spot is a storm 1.3× the diameter of Earth, observed since 1665.',
      "Its magnetic field is 20,000× stronger than Earth's.",
      'Acts as a "cosmic vacuum cleaner", deflecting comets away from inner planets.',
    ],
    atmosphere: { Hydrogen: 90, Helium: 10 },
    notableFeatures: [
      'Great Red Spot',
      'Galilean moons',
      'Faint ring system',
      'Powerful magnetosphere',
    ],
  },
  {
    planet: 'SATURN',
    facts: [
      'Ring system is mostly water ice with traces of rock and dust.',
      'The rings will likely disappear in 100–300 million years as material rains down.',
      'Hexagonal cloud pattern at the north pole is ~30,000 km wide.',
      'Has 146 known moons — more than any other planet.',
    ],
    atmosphere: { Hydrogen: 96, Helium: 3, Other: 1 },
    notableFeatures: [
      'Ring system',
      'Hexagonal polar storm',
      'Titan',
      'Enceladus geysers',
    ],
  },
  {
    planet: 'URANUS',
    facts: [
      'Rotates on its side, possibly knocked over by a collision early in its history.',
      'Has 13 faint rings and 27 known moons named after Shakespeare characters.',
      'Coldest planetary atmosphere in the solar system: −224 °C.',
      'Discovered in 1781 by William Herschel — first planet found with a telescope.',
    ],
    atmosphere: { Hydrogen: 83, Helium: 15, Methane: 2 },
    notableFeatures: [
      '98° axial tilt',
      'Faint ring system',
      'Methane-blue color',
    ],
  },
  {
    planet: 'NEPTUNE',
    facts: [
      'Fastest winds in the solar system, reaching 2,100 km/h.',
      'Triton orbits backward — likely a captured Kuiper Belt object.',
      "Was predicted mathematically before being observed, based on Uranus's orbit.",
      'A single year lasts 165 Earth years — only completed one orbit since its 1846 discovery.',
    ],
    atmosphere: { Hydrogen: 80, Helium: 19, Methane: 1 },
    notableFeatures: ['Great Dark Spot', 'Triton', 'Supersonic winds'],
  },
];

export const TRIVIA_BY_PLANET: Map<PlanetName, Trivia> = new Map(
  TRIVIA.map(t => [t.planet, t]),
);
